_target_: src.models.leak_detection_distance_module_transfer.LeakDetectionTransferModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

checkpoint_file: Null
gamma: 1
from_scratch: false
use_representation: true
use_material: true
freezed_layers: []